services:
  - type: web
    name: referral-backend
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: autorack.proxy.rlwy.net
      - key: DB_PORT
        value: 35993
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: wJfssrKpgaXPSpxqFuVDdTKCtzwJvWkV
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://autorack.proxy.rlwy.net:35993/railway?allowPublicKeyRetrieval=true&useSSL=false

  - type: web
    name: referral-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: referral-backend
          property: url
