server.port=${PORT:8080}
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://autorack.proxy.rlwy.net:35993/railway?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:wJfssrKpgaXPSpxqFuVDdTKCtzwJvWkV}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

Custom properties
referral.jwt.secret=${JWT_SECRET:9a4f2c8d3b7e1f6g5h4i3j2k1l0m9n8o7p6q5r4s3t2u1v0wxy}
referral.jwt.expiration=86400000
